name: 构建和发布

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write  # 这给予了创建 release 的权限
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: 构建可执行文件
      run: pyinstaller --onefile --windowed --add-data "data:data" git/main.py
    
    - name: 创建 Release
      id: create_release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: 上传 Release 资产
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/main.exe
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: 输出 Release URL
      run: |
        echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/v${{ github.run_number }}"
      shell: bash
